name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
