name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry --pip-args=--pre
    
    - name: Configure poetry
      shell: bash
      run: poetry config virtualenvs.prefer-active-python true
    
    - uses: dmitry-shibanov/setup-python@v-dmshib/fix-poetry-parsing
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
